server:
    port: 3000
    connectionTimeout: 15 # The duration for which the server gracefully wait for existing connections to finish in seconds.

database:
    host: "localhost"
    port: 5432
    name: ""
    user: ""
    pass: ""
